#!/bin/bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

WARNING_LEVEL=25
CHARGED_LEVEL=95
BATTERY_DISCHARGING=`acpi -b | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -P -o "[0-9]+(?=%)"`

EMPTY_FILE=/tmp/battery-empty
FULL_FILE=/tmp/battery-full

if [ $BATTERY_DISCHARGING -eq 1 ] && [ -f $FULL_FILE ]; then
    rm $FULL_FILE
elif [ $BATTERY_DISCHARGING -eq 0 ] && [ -f $EMPTY_FILE ]; then
    rm $EMPTY_FILE
fi

if [ $BATTERY_DISCHARGING -eq 0 ] && [ $BATTERY_LEVEL -gt $CHARGED_LEVEL ] && [ ! -f $FULL_FILE ]; then
    notify-send "Battery Charged" "Battery is fully charged" -i "battery" -r 9991
    touch $FULL_FILE
elif [ $BATTERY_DISCHARGING -eq 1 ] && [ $BATTERY_LEVEL -le $WARNING_LEVEL ] && [ ! -f $EMPTY_FILE ]; then
    notify-send "Low Battery" "${BATTERY_LEVEL}% remaining" -u critical -i "battery-alert" -r 9991
    touch $EMPTY_FILE
fi
