#!/bin/bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

WARNING_LEVEL=25
CHARGED_LEVEL=95
BATTERY_DISCHARGING=`acpi -b | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -P -o "[0-9]+(?=%)"`

notify-send "Battery Charged" "Battery is fully charged" -i "battery" -r 9991
