#! /bin/sh

LAYOUT_ROOT="$TX_ROOT/layouts"

usage() {
    cat <<EOF
Usage:
    -h | --help | help       --  show this help message
    (-l | --layout) [layout] --  create a new layout or edit existing one
    --ls | ls                --  show running sessions and layouts
    [layout]                 --  create new session from the given layout, or a blank session with the given name
    (no arguments)           --  attach to the last active session
EOF
}

list() {
    sessions=$(tmux ls | awk -F '[:,()]' '{print $1}')

    layouts=$(
        find "$TX_ROOT/layouts" -type f -name '*.layout.sh' -exec basename {} .layout.sh \; | while read -r layout; do
            echo "$sessions" | grep -qx "$layout"
            if [ $? -ne 0 ]; then
                echo "$layout"
            fi
        done
    )

    max_len=$( { echo "$sessions"; echo "$layouts"; } | awk '{print length}' | sort -nr | head -1 )

    tmux ls | awk -v max_len="$max_len" -F '[:,()]' '{printf "%-*s (session) (%d windows)%s\n", max_len, $1, $2, ($0 ~ /attached/) ? " (attached)" : ""}'
    echo "$layouts" | awk -v max_len="$max_len" '{printf "%-*s (layout)\n", max_len, $1}'
}

example_layout() {
    cat > $2 <<EOF
. $TX_ROOT/functions.sh

# Set up project with a root dir, and name
project_root ~
session_name "$1"

# create your session
new_session

# layout your session
rename_window "code"
run_command "nvim"

new_window "servers"
split_horizontal 50%

# select the window you want first
select_window "code"

# attach to your session
attach_to_session
EOF
}

new_session() {
    tmux_sessions=$(tmux ls | awk -F '[:,()]' '{print $1}')

    if echo "$tmux_sessions" | grep -qx "$1"; then
        tmux_attach_or_switch $1
        return
    fi

    layouts=$(ls "$LAYOUT_ROOT")

    if echo "$layouts" | grep -qx "$1.layout.sh"; then
        . "$LAYOUT_ROOT/$1.layout.sh"
        return
    fi

    tmux new-session -d -s "$1"
    tmux_attach_or_switch $1
}

tmux_attach_or_switch() {
    if [ -z "$TMUX" ]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

editor_session() {
    file="$LAYOUT_ROOT/$1.layout.sh"

    if [[ ! -f $file ]] then
        example_layout $1 $file
    fi

    $EDITOR $file
}

if [[ $# -gt 0 ]]; then
    case "$1" in
        --ls | ls)
            list
            ;;
        -h | --help | help)
            usage
            ;;
        -l | --layout)
            if [[ -n "$2" && "$2" != --* ]]; then
                editor_session "$2"
            else
                echo "Error: --layout requires a value"
                usage
            fi
            ;;
        *)
            new_session $1
            ;;
    esac
else
    if [ -z "$TMUX" ]; then
        tmux attach
    else
        echo "Error: already attached"
        exit 1
    fi
fi
