#!/bin/sh

NIGHT_TEMP="3000"
DAY_TEMP="6500"
CMD="redshift -P -O"
FILE="/tmp/redshift"

store_temp() {
    echo "$1" > $FILE
}

if [[ $# -gt 0 ]]; then
    case "$1" in
        on)
            $CMD "$NIGHT_TEMP"
            store_temp "$NIGHT_TEMP"
            ;;
        off)
            $CMD "$DAY_TEMP"
            store_temp "$DAY_TEMP"
            ;;
        query)
            if [ ! -f "$FILE" ]; then
                echo 0
                exit 0
            fi

            temp=$(cat "$FILE")

            if [ "$temp" -gt 5000 ]; then
                echo 0
            else
                echo 1
            fi
            ;;
        *)
            if ! [[ "$1" =~ ^[0-9]+$ ]]; then
                echo "Error: Argument is not a number."
                exit 1
            elif [ "$1" -lt 1000 ] || [ "$1" -gt 25000 ]; then
                echo "Error: Number is out of valid range (1000-25000)."
                exit 1
            fi

            $CMD "$1"
            store_temp "$1"
            ;;
    esac
else
    exit 1
fi
